apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: open-policy-agent
deploy:
  kustomize:
    paths:
    - k8s/overlay/minikube

profiles:
  - name: openshift
    deploy:
      kustomize:
        paths:
          - k8s/overlay/openshift

