apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  appGroup: opa

namespace: default

resources:
  - ../../base

images:
  - name: c3smonkey/template
    newName: docker.io/openpolicyagent/opa
    newTag: 0.25.2-rootless
