spring:
  profiles:
    active: default
    include: common,security

  application:
    name:  opa-demo

    jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    ch.keepcalm.security: TRACE
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} - %clr(${spring.application.name:-}){green} - %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"



