spring:
  profiles:
    active: default
    include: common
  application:
    name:  opa-demo

    jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true


logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
