keepcalm:
  security:
    access-decision-voter:
      voters: OPA
      url: http://localhost:8181/v1/data/http/authz/allow
    jwt:
      issuer: Keepcalm Auth
      audience: Keepcalm
      secret: s3cretP@ssw0rd
    endpoints:
      admin:
        - "/api/salary/**"
      user:
        - "/api/document/**"
      unsecured:
        - "/unsecure"

logging:
  level:
    ch.keepcalm.security: TRACE
  pattern:
    console: "%clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"

